server:
  port: 9090

#DataBase Properties
spring:  datasource:    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver

#hibernate auto property  jpa:    hibernate:      ddl-auto: update
    show-sql: true 

#multipart configuration  servlet:    multipart:      max-file-size: 10MB
      max-request-size: 10MB
      
#Authentication credentials  
   
project:
  image: images/          #Log property
logging:  level:    '[org.springframework.security]': DEBUG

#app Messages
blog_api:
  messages:
    deleteSuccMsg: Deleted Successfully !!
    defaultImgName: default.png
    
    
    
    
    